name: vrnn
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.10.0
  - pandas
  - numpy
  - scipy
  - jupyterlab
  - pyg-lib
  - pygod
  - pytorch
  - torchvision 
  - torchaudio 
  - scikit-learn
  - matplotlib
